# .github/workflows/cypress-tests.yml

name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"h
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: bun run build
          start: bun start
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
